name: Pull Request Labels
on:
  pull_request:
    types: [labeled, unlabeled]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "hacktoberfest-accepted"
